#
###################################
# Site wide configuration
####################################
#
title: beaudry.io
email: 
description: A blog about the cloud, and modern tooling.
url: https://beaudry.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Eastern/NewYork
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Joe Beaudry
  avatar: me.jpg
  job: "Systems Engineer"
  bio: "An Engineer who loves learning new things, developing for the cloud, and helping to streamline processes."
  email:
  disqus-shortname: beaudry
  twitter: joebeau93
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: beaudryj
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: josephebeaudry
  xing: #username
  instagram: joebeau93
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
